### ISSUE TITLE
[BUG] Cannot Create TicketNotesChild resources; 400 bad request

### ISSUE THREAD

**Issue by MysticCodeCruncher** [KelvinTegelaar/AutotaskAPI#44]
Description:
The New-AutotaskAPIResource function is not able to POST TicketNotesChild resources because it is not replacing the string "{ParentID}" for the $resourceURL variable

```
$Body = New-AutotaskBody -Resource TicketNotesChild -NoContent
$Body.id = "0"
$Body.ticketID = "$($variable_containing_ticketID)"
$Body.description = "This is a note added by script"
$Body.noteType = "1"
$Body.publish = "2"
$Body.title = "Note Added By Script"
New-AutotaskAPIResource -Resource TicketNotesChild -body $body -verbose
```

Results in the following error :
```
VERBOSE: POST https://webservices3.autotask.net/atservicesrest//V1.0/Tickets/{parentId}/Notes with -1-byte payload
New-AutotaskAPIResource : Connecting to the Autotask API failed. The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ New-AutotaskAPIResource -Resource TicketNotesChild -Body $body -Verbo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AutotaskAPIResource
```

**Expected behavior**
It creates the ticket note for the specified ticketID

Desktop:
OS: Windows 10
PowerShell version: 5.1.19041.1682

**Comment by KelvinTegelaar** [comment]
There was a version difference between the uploaded version to the gallery and the github version. this is resolved now. :)

**Comment by MysticCodeCruncher** [comment]
Thank you for updating the gallery version to match GitHub's version however I am still getting a warning trying to create TicketNotesChild items (after updating to the latest module in the gallery):

WARNING: You must specify a parentId when creating a child resource
![warning](https://user-images.githubusercontent.com/81263856/186981836-dbcde1e4-b95d-4b10-ac47-6d4385ff2c89.png)
